on:
  push:
    branches:
      - main
    paths:
      - 'airflow-base/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
   
  call:
    needs: build
    uses: nombase/test-repo/.github/workflows/cicd.yaml@main