on:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - 'airflow/**'
      - '!airflow-base/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2